version: '3'
services:
  web:
    build:
      context: ./myweb
      dockerfile: Dockerfile
    container_name: myweb
    ports:
      - "80:80"
    volumes:
      - ./myweb:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhobbies
      MYSQL_USER: kittinun
      MYSQL_PASSWORD: 65130695
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
volumes:
  db_data:
