version: "3.3"
services:
  web:
    build:
      context: ./myweb
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - db
    volumes:
      - ./myweb:/var/www/html/
    ports:
      - 8081:80
  db:
    container_name: mysql
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhobbies
      MYSQL_USER: kittinun
      MYSQL_PASSWORD: 65130695
    ports:
      - 6033:3306