version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: myhobbies
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kittinun
      MYSQL_PASSWORD: 65130695
      MYSQL_DATABASE: myhobbies
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/myhobbies.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script

  web:
    build: .
    container_name: myhobbies-web
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    
volumes:
  db_data: