version: "3.3"
services:
  web:
    build:
      context: ./myweb
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - db
    volumes:
      - ./myweb:/var/www/html/
    ports:
      - 80:80

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kittinun
      MYSQL_PASSWORD: 65130695
      MYSQL_DATABASE: myhobbies
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/myhobbies.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:









        