version: "3.3"
services:
  web:
    build:
      context: ./myweb
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - db
    volumes:
      - ./myweb:/var/www/html/
    ports:
      - 80:80
    networks:
      - internal
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kittinun
      MYSQL_PASSWORD: 65130695
      MYSQL_DATABASE: myhobbies
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    networks:
      - internal

networks:
  internal:

volumes:
  db_data:







        