version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhobbies
      MYSQL_USER: kittinun
      MYSQL_PASSWORD: 65130695
    volumes:
      - ./mysql/myhobbies.sql:/docker-entrypoint-initdb.d

volumes:
  db_data:

