version: "3.3"
services:
  web:
    build:
      context: ./myweb
      dockerfile: Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./myweb:/var/www/html/
    ports:
      - 80:80

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kittinun
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: myhobbies
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:









        