version: "3.3"
services:
  web:
    build:
      context: ./myweb
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - db
    volumes:
      - ./myweb:/var/www/html/
    ports:
      - 8081:80
    networks:
      - internal
  db:
    image: mariadb
    container_name: my_mariadb
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhobbies
      MYSQL_USER: kittinun
      MYSQL_PASSWORD: 65130695
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - internal
volumes:
  mariadb_data: 
networks:
    internal:
      driver: bridge 